# Goal

Convert the file `subject_code_lookup.json` to a more usable Excel file.

In [1]:
import pandas as pd

In [4]:
codes = pd.read_json('subject_code_lookup.json')
codes.info()
codes.head()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, area to abbrev
Columns: 325 entries, 2735 to 2101
dtypes: object(325)
memory usage: 5.1+ KB

,2735,2736,2728,2808,2729,2700,2806,2403,2739,2716,...,2104,1404,2609,1801,3615,1905,1402,1410,2216,2101
area,"Pediatrics, Perinatology and Child Health",Pharmacology (medical),Neurology (clinical),Neurology,Obstetrics and Gynecology,Medicine (all),Developmental Neuroscience,Immunology,"Public Health, Environmental and Occupational ...",Genetics (clinical),...,Nuclear Energy and Engineering,Management Information Systems,Logic,Decision Sciences (miscellaneous),Respiratory Care,Economic Geology,Accounting,Industrial Relations,Architecture,Energy (miscellaneous)
abbrev,MEDI,MEDI,MEDI,NEUR,MEDI,MEDI,NEUR,IMMU,MEDI,MEDI,...,ENER,BUSI,MATH,DECI,HEAL,EART,BUSI,BUSI,ENGI,ENER

In [7]:
df = pd.DataFrame(
    {
        'Code': list(codes.columns),
        'Area': codes.loc['area', :],
        'Abbreviation': codes.loc['abbrev', :]        
    }
).reset_index(drop=True)

In [8]:
df

     Code                                       Area Abbreviation
0    2735  Pediatrics, Perinatology and Child Health         MEDI
1    2736                     Pharmacology (medical)         MEDI
2    2728                       Neurology (clinical)         MEDI
3    2808                                  Neurology         NEUR
4    2729                  Obstetrics and Gynecology         MEDI
..    ...                                        ...          ...
320  1905                           Economic Geology         EART
321  1402                                 Accounting         BUSI
322  1410                       Industrial Relations         BUSI
323  2216                               Architecture         ENGI
324  2101                     Energy (miscellaneous)         ENER

[325 rows x 3 columns]

In [9]:
df.to_excel('/media/Bibliometrics/matt analysis/subject_codes_lookup.xlsx', index=False)